# Generated by Django 5.0.6 on 2024-06-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favouritemovies',
            fields=[
                ('favourite_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favouritemovies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.TextField()),
                ('password_hash', models.BinaryField()),
                ('salt', models.BinaryField()),
                ('display_name', models.TextField()),
                ('user_role', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
